# Generated by Django 3.2.7 on 2022-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0002_alter_rightanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightanswer',
            name='question_id',
            field=models.IntegerField(default=1),
        ),
    ]
