# Generated by Django 4.0.6 on 2022-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0003_rightanswer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='answer',
            name='true',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choices',
            name='true',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='RightAnswer',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
