# Generated by Django 4.0.6 on 2022-07-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0004_remove_answer_answer_remove_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='right_answer_id',
        ),
    ]
