# Generated by Django 4.0.6 on 2022-07-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0006_alter_choices_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
