# Generated by Django 4.0.6 on 2022-07-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0007_response_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, to='Dino.answer'),
        ),
    ]
