# Generated by Django 4.0.6 on 2022-07-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0008_remove_response_answer_response_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='true',
            field=models.BooleanField(default=False),
        ),
    ]
